# mainatiner: nick.reva@snap.com
ENV["TERM"]="linux"

Vagrant.configure("2") do |config|
#test for Yi!
  # set up root access
  # config.ssh.username = 'root'
  config.ssh.password = 'vagrant'
  config.ssh.insert_key = 'true'

  NodeCount = 1

  # configure Kubernetes Nodes
  (1..NodeCount).each do |i|
    config.vm.define "node#{i}" do |node|
      # set base image for the vagrant box
      config.vm.box = "opensuse/Leap-15.2.x86_64"
      #config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/id_rsa.pub"
      #config.vm.provision "file", source: "~/.ssh/id_rsa", destination: "~/.ssh/id_rsa"
      #config.ssh.insert_key = 'false'
      
      # set the static IP for the vagrant box
      node.vm.network "private_network", ip: "192.168.50.10#{i}"
      # configure the parameters for VirtualBox provider
      node.vm.provider "virtualbox" do |v|
        v.name = "node#{i}"
        v.memory = 2048
        v.cpus = 2
      end
    # copy the private_key for default VM started with virtualbox provider to user vagrant if using vagrant
    # cp -p /vagrant/.vagrant/machines/node1/virtualbox/private_key /home/vagrant/.ssh/id_rsa
    # config.vm.provision "file", source: "~/codebase/pythonProjects/nd064-c3-microservices-security-project-starter/starter/.vagrant/machines/node1/virtualbox/private_key", destination: "~/.ssh/id_rsa"

    config.vm.provision "shell", inline: <<-SHELL
      sudo zypper --non-interactive install apparmor-parser
    SHELL
    config.vm.provision "shell", path: "bootstrap.sh"
    end
  end
end
